spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userRegistrationDB
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mohit
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      format_sql: true
